# Cloudflare Workers configuration file

name = "lamontai"
main = "./.next/standalone/server.js"
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "npm run cloudflare:build"

[site]
bucket = "./.next/static"

[env.production]
# Production-specific settings
NODE_ENV = "production"
LOG_LEVEL = "warn"

[env.development]
# Development-specific settings
NODE_ENV = "development"
LOG_LEVEL = "debug"

# Add necessary bindings for Cloudflare services
# Visit https://developers.cloudflare.com/workers/configuration/bindings/
[[kv_namespaces]]
binding = "CACHE"
id = "" # Replace with your KV namespace ID

# Configure limits for the Workers environment
[limits]
cpu_ms = 50  # Maximum CPU time in milliseconds
memory_mb = 128  # Maximum memory in MB 