'use client'

import React, { useState } from 'react'
import Container from '../ui/Container'
import Button from '../ui/Button'

interface FAQItem {
  question: string
  answer: string
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  const faqs: FAQItem[] = [
    {
      question: 'How does the AI create SEO-optimized content?',
      answer: 'Our AI uses advanced natural language processing and machine learning trained on high-ranking content. It analyzes top-performing articles in your niche, identifies key topics, semantic keywords, and optimal structure. Then it generates original content following SEO best practices including proper heading hierarchy, keyword placement, readability metrics, and semantic richness that Google rewards.'
    },
    {
      question: 'Can I edit the AI-generated content?',
      answer: 'Absolutely! While our AI produces high-quality content, you have complete freedom to edit, refine, or expand upon the generated articles. Our editor interface makes it easy to adjust the content to your exact preferences and brand voice, ensuring the final result perfectly matches your vision.'
    },
    {
      question: 'How does the pricing work? Are there any hidden fees?',
      answer: 'Our pricing is completely transparent with no hidden fees. You pay a fixed monthly subscription based on your chosen plan, which includes a set number of articles per month and specific features. You can upgrade, downgrade, or cancel your subscription at any time. All plans include a 7-day free trial so you can test the platform before being charged.'
    },
    {
      question: 'Is the content plagiarism-free?',
      answer: 'Yes, all content generated by our AI is 100% original and plagiarism-free. Our system creates unique content from scratch rather than copying existing text. We have built-in safeguards to ensure originality, and you can run the content through plagiarism checkers for additional peace of mind.'
    },
    {
      question: 'Can I integrate with WordPress or other CMSs?',
      answer: 'Yes! We offer seamless integration with WordPress, Shopify, Webflow, and most major content management systems. You can publish directly from our platform to your CMS with just a few clicks, or export the content in various formats including HTML, Markdown, or plain text.'
    },
    {
      question: 'Do I need SEO experience to use this tool?',
      answer: 'No SEO experience is required. Our platform is designed to be user-friendly for beginners while offering advanced features for SEO experts. We provide helpful guidance throughout the content creation process, and our AI handles the technical SEO optimization automatically. If you do have SEO knowledge, you can customize the settings to align with your specific strategy.'
    }
  ]

  return (
    <section id="faq" className="py-20 bg-gray-50">
      <Container>
        <div className="text-center mb-16 max-w-3xl mx-auto">
          <div className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4">
            FAQ
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600">
            Everything you need to know about our AI content generation tool.
          </p>
        </div>

        <div className="max-w-3xl mx-auto divide-y divide-gray-200 rounded-xl overflow-hidden">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-white">
              <button
                onClick={() => toggleFAQ(index)}
                className="flex justify-between items-center w-full p-6 text-left focus:outline-none"
              >
                <h3 className="text-lg font-medium text-gray-900">{faq.question}</h3>
                <span className="ml-6 flex-shrink-0">
                  {openIndex === index ? (
                    <svg className="h-6 w-6 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                    </svg>
                  ) : (
                    <svg className="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  )}
                </span>
              </button>
              {openIndex === index && (
                <div className="p-6 pt-0">
                  <p className="text-gray-600 leading-relaxed">{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="text-center mt-16">
          <p className="text-gray-600 mb-6">Still have questions?</p>
          <Button href="/contact" variant="primary" className="px-6 py-3">
            Contact Support <span aria-hidden="true">→</span>
          </Button>
        </div>
      </Container>
    </section>
  )
} 